# Google Cloud Run configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cv-screener-automateengage
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/cv-screener:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: APP_NAME
          value: "CV Automation MVP"
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.1"
            memory: "256Mi"